feat: implemented statistics server
NikitaBuffy/java-explore-with-me pull request #3
Opened 2023-06-15 08:49 UTC by NikitaBuffy

2023-06-15 22:57 UTC, db-exp requested changes

2023-06-15 22:57 UTC, db-exp commented on stats/stats-client/src/main/resources/application.properties
> +stats-server.url=http://localhost:9090
лучше бы из docker-compose прокинуть

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/controller/StatsController.java
> +                LocalDateTime.parse(end, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), uris, unique);
ateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") - может в константу?

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/HitMapper.java
> +//    public static HitDto hitToDto(Hit hit) {
на удаление?

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/HitMapper.java
> +                LocalDateTime.parse(hitDto.getTimestamp(), DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") - может одну константу на сервис?

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/resources/schema.sql
> +    app VARCHAR(255) NOT NULL,
кажется, много

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/Hit.java
> +    private String uri;
давай тоже размер проставим как в схеме

2023-06-15 22:57 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/Hit.java
> +    private String app;
давай тоже размер проставим как в схеме

2023-06-15 22:57 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/explorewithme/statsclient/StatsClient.java
> +    private static final String STAT_SERVER_URL = "${stats-server.url}";
кажется, что лучше более явно заиженктить проперти через Value или через конструктор

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/controller/StatsController.java
> +                LocalDateTime.parse(end, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), uris, unique);
Сделал общую константу на сервис

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/HitMapper.java
> +                LocalDateTime.parse(hitDto.getTimestamp(), DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
Сделал общую константу на сервис

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/HitMapper.java
> +//    public static HitDto hitToDto(Hit hit) {
Удалил

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/resources/schema.sql
> +    app VARCHAR(255) NOT NULL,
Сделал меньше

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/Hit.java
> +    private String uri;
Указал

2023-06-18 12:26 UTC, NikitaBuffy commented on stats/stats-server/src/main/java/ru/practicum/explorewithme/statsserver/model/Hit.java
> +    private String app;
Указал

2023-06-18 12:33 UTC, NikitaBuffy commented on stats/stats-client/src/main/resources/application.properties
> +stats-server.url=http://localhost:9090
Не нашел явного способа передать через docker-compose, так как stats-client нет в docker-compose, а создавать контейнер и образ для него нам не нужно.

2023-06-18 13:03 UTC, db-exp approved these changes

2023-06-18 13:06 UTC, merged