feat: implements main service
NikitaBuffy/java-explore-with-me pull request #4
Opened 2023-06-25 14:26 UTC by NikitaBuffy

2023-06-25 17:40 UTC, db-exp requested changes

2023-06-25 17:40 UTC, db-exp commented on main/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +    private final EventRepository eventRepository;
Совет - используй "чужие" сервисы, а не репозитории и связность будет меньше

2023-06-25 17:40 UTC, db-exp commented on stats/stats-client/src/main/java/ru/practicum/ewm/statsclient/StatsClient.java
> +        this.rest = new RestTemplate();
RestTemplate лучше создавать один раз в конфигурации как бин и дальше просто инжектить

2023-06-25 17:40 UTC, db-exp commented on stats/stats-server/src/main/java/ru/practicum/ewm/statsserver/controller/StatsController.java
> +                                   @RequestParam(required = false) String[] uris,
Вместо массива можно список

2023-06-25 20:07 UTC, NikitaBuffy commented on main/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +    private final EventRepository eventRepository;
Спасибо за совет, учту на будущее. Как я понял, лучше тогда в EventService создать отдельный метод, который будет делать запрос findByCategoryId, а уже в текущем классе просто вызывать метод из чужого сервиса. 

А что касается других сервисов, того же EventServiceImpl, который пользуется многими репозиториями и разными запросами у них. Тоже лучше делать через чужие сервисы и создавать отдельные методы у них? Ведь сейчас там исключительно бизнес-логика эндпоинтов, а добавится еще условно десяток методов, не связанных с контроллером.

2023-06-25 20:08 UTC, NikitaBuffy commented on main/src/main/java/ru/practicum/ewm/exception/CategoryNotFoundException.java
> +public class CategoryNotFoundException extends EntityNotFoundException {
Спасибо за совет, поправлю в будущем

2023-06-26 08:28 UTC, db-exp commented on main/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +    private final EventRepository eventRepository;
"Как я понял, лучше тогда в EventService создать отдельный метод, который будет делать запрос findByCategoryId, а уже в текущем классе просто вызывать метод из чужого сервиса." - да
". Тоже лучше делать через чужие сервисы и создавать отдельные методы у них? Ведь сейчас там исключительно бизнес-логика эндпоинтов, а добавится еще условно десяток методов, не связанных с контроллером." - смысл вызова чужих сервисов - изоляция внутренней кухни по данным, если кому то нужны данные этого сервиса, то это оборачиваем в метод и вызываем его, а не репозиторий напрямую. Ведь сервис может быть и просто оберткой удаленного вызова, например

2023-06-26 08:28 UTC, db-exp approved these changes

2023-06-26 17:24 UTC, NikitaBuffy commented on main/src/main/java/ru/practicum/ewm/service/category/CategoryServiceImpl.java
> +    private final EventRepository eventRepository;
Спасибо за ответ! Буду придерживаться этой системы в дальнейшем

2023-06-26 17:25 UTC, merged